name: TradeMeGemsAddon
main: me.drkmatr1984.TradeMeGemsAddon.TradeMeGemsAddon
version: 1.0
author: DrkMatr1984
description: Allows the user to use Gems from ElementalGems or MinevoltGems as currency in TradeMe by Zrips
depend: [TradeMe]
softdepend: [MinevoltGems, ElementalGems]
permissions:
    trademe.gemstrade:
        description: Allows the user to use Gems from ElementalGems or MinevoltGems as currency in TradeMe by Zrips
        default: true